setTimeout(() => {
    console.log("hackig wifi user name and password ")
}, 2000);
try {
    // setTimeout(()=> {
    //     console.log(harry)
    // },200) 
    //set timeout  ke andar try cstch bhi error handle nhi kar sakta error handle ke liye hmko settime out ke andar bhi try catcch dalna hoga 
    console.log(harry)
}
catch (err)
{
    console.log("Haa haa ho ho" + err); 
}
setTimeout(() => {
    console.log("fetching  user name and password ")
},4000);
setTimeout(() => {
    console.log("the user (998899789890 name and passaward(*******) is  ")
},6000);
setTimeout(() => {
    console.log("mr harry your password hacked ")
}, 8000);

